name: "Install python env"
description: "Install cached python env with poetry"

runs:
  using: "composite"
  steps:

  - name: Cache Python
    uses: actions/cache@v2
    with:
      path: /opt/hostedtoolcache/Python/3.10.4
      key: python-3.10.4

  - name: Install Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.10.4

  # https://www.peterbe.com/plog/install-python-poetry-github-actions-faster
  - name: Cache $HOME/.local
    uses: actions/cache@v2
    with:
      path: ~/.local
      key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/actions/install-python-env/action.yml') }}

  - name: Install Poetry
    uses: abatilo/actions-poetry@v2.1.3

  # https://stackoverflow.com/questions/62977821/how-to-cache-poetry-install-for-github-actions
  - name: Cache venv
    id: cache-venv
    uses: actions/cache@v2
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

  - name: Create python virtualenv
    shell: bash
    run: python -m venv .venv
    if: steps.cache-venv.outputs.cache-hit != 'true'

  - name: Install dependencies
    run: |
      source .venv/bin/activate
      poetry config experimental.new-installer false
      poetry install
    shell: bash
    if: steps.cache-venv.outputs.cache-hit != 'true'
